version: "3.9"

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: user
      POSTGRES_DB: db_musica
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./musica/:/code
    ports:
      - "8000:8000"
    depends_on:
        - db

volumes:
    postgres:
