# Generated by Django 3.2.4 on 2021-06-24 06:50
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disquera", "0001_initial"),
        ("artista", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("anio_lanzamiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nacionalidad", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Cancion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("anio_lanzamiento", models.DateField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("editado", models.DateTimeField(auto_now=True)),
                ("album", models.ManyToManyField(to="canciones.Album")),
                ("artista", models.ManyToManyField(to="artista.Artista")),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="canciones.autor",
                    ),
                ),
                ("disquera", models.ManyToManyField(to="disquera.Disquera")),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
