# Generated by Django 3.2.4 on 2021-06-24 15:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("canciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="nombre",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
