# Generated by Django 3.2.5 on 2021-07-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_autor_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre']},
        ),
    ]
