# Generated by Django 3.2.4 on 2021-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disquera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('genero', models.CharField(blank=True, choices=[('POP', 'POP'), ('ROCK', 'ROCK'), ('RANCHERO', 'RANCHERO')], default='POP', help_text='Genero del artisita', max_length=8, null=True)),
                ('disquera', models.ManyToManyField(to='disquera.Disquera')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
