# Generated by Django 3.2.4 on 2021-06-24 06:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disquera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("editado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
